spring.application.name=MyAPI

server.port=8080

db.server=jdbc:sqlserver://localhost\\SQLEXPRESS;encrypt=true;trustServerCertificate=true
db.dbName=UsersProfile
db.username=ron
db.password=P@ssw0rd123

